name: CI Checks

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: 'ubuntu-latest'
      working-directory:
        required: false
        type: string
        default: '.'
      setup:
        required: false
        type: string
        default: ''
      format:
        required: true
        type: string
      lint:
        required: true
        type: string
      build:
        required: true
        type: string
      test:
        required: true
        type: string
    secrets:
      github-token:
        required: false

jobs:
  format:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - if: inputs.setup != ''
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.setup }}
      - working-directory: ${{ inputs.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        run: ${{ inputs.format }}

  lint:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - if: inputs.setup != ''
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.setup }}
      - working-directory: ${{ inputs.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        run: ${{ inputs.lint }}

  build:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - if: inputs.setup != ''
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.setup }}
      - working-directory: ${{ inputs.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        run: ${{ inputs.build }}

  test:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - if: inputs.setup != ''
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.setup }}
      - working-directory: ${{ inputs.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        run: ${{ inputs.test }}
