name: CI Checks

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: 'ubuntu-latest'
      working-directory:
        required: false
        type: string
        default: '.'
      setup:
        required: false
        type: string
        default: ''
      format:
        required: false
        type: string
        default: ''
      lint:
        required: false
        type: string
        default: ''
      build:
        required: false
        type: string
        default: ''
      test:
        required: false
        type: string
        default: ''

jobs:
  format:
    if: inputs.format != ''
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - if: inputs.setup != ''
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.setup }}
      - working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.format }}

  lint:
    if: inputs.lint != ''
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - if: inputs.setup != ''
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.setup }}
      - working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.lint }}

  build:
    if: inputs.build != ''
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - if: inputs.setup != ''
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.setup }}
      - working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.build }}

  test:
    if: inputs.test != ''
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - if: inputs.setup != ''
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.setup }}
      - working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.test }}
